platform:
    - x64

cache:
    - C:\Users\appveyor\.esy\3_\i
    - C:\Users\appveyor\.esy\source-tarballs

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.3.0
    # Retry is necessary due to esy/esy#413 and esy/esy#414
    - appveyor-retry esy install

build_script:
    - node scripts/gen_link_flags.js
    - esy build
    # Copy over dynamic libs for SSL (libcrypto & libssl)
    - esy b ./scripts/copy_ssl_runtime_win.sh
    - _build\install\default\bin\fpack.exe --version

test: off
